name: Update dev version
on:
  push:
  workflow_dispatch:

jobs:
  update_version:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          install-r: false
          
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::desc

      - name: Update version
        id: vars
        run: |
          invisible(desc::desc_bump_version("dev"))
          new_version = desc::desc_get_version()
          cat(sprintf("PKG_NEW_VERSION=%s\n", new_version), 
              file = Sys.getenv("GITHUB_ENV"), append = TRUE)
          message("Setting PKG_NEW_VERSION to ", new_version)
        shell: Rscript {0}
        
      - name: Commit the version change
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update dev version (Github Actions)'

      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ env.PKG_NEW_VERSION }}',
              sha: context.sha
            })
