on: push

name: Update dev version

jobs:
  update_version:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          install-r: false
          
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::desc

      - name: Update version
        id: vars
        run: |
          desc::desc_bump_version("dev")
          new_version = desc::desc_get_version()
          cat(sprintf("PKG_NEW_VERSION=%s\n", new_version), 
              file = Sys.getenv("GITHUB_ENV"), append = TRUE)
          message("Setting PKG_NEW_VERSION to ", new_version)
        shell: Rscript {0}

      - name: Commit the version change
        uses: EndBug/add-and-commit@v7.5.0
        with:
          default_author: github_actions
          message: 'Update dev version (Github Actions)'
