on: push

name: Update dev version

jobs:
  update_version:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          install-r: false

      - name: Update version
        run: |
          install.packages("desc")
          desc::desc_bump_version("dev")
        shell: Rscript {0}

      - name: Commit the version change
        uses: EndBug/add-and-commit@v7.5.0
        with:
          default_author: github_actions
          message: 'Update dev version (Github Actions)'
